Repository swiftlang/swift-driver, pull requests merged in 2024-01, with the labels that each got.

#1516 Don't pass `-rpath` and `-lswiftCore` in embedded mode
  Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
  Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
  Tests/SwiftDriverTests/SwiftDriverTests.swift
Labels: bug, embedded

#1514 Add `m68k` to `Triple.swift`
  Sources/SwiftDriver/Utilities/Triple.swift
  Tests/SwiftDriverTests/TripleTests.swift
Labels: NFC

#1512 [NFC] Add `Decodable` conformance to `Triple.Arch`
  Sources/SwiftDriver/Utilities/Triple.swift
Labels: NFC

#1517 [Embedded] correct link paths when building for embedded to avoid stray response file paths
  Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
  Tests/SwiftDriverTests/SwiftDriverTests.swift
Labels: bug

#1533 Embedded: don't link `swiftrt.o` for bare metal
  Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
  Tests/SwiftDriverTests/SwiftDriverTests.swift
Labels: bug, embedded
