Repository swiftlang/swift-driver, pull requests merged in 2024-07, with the labels that each got.

#1652 [6.0 🍒][PrebuiltModuleGen] Ensure the dependency scanner always ignores existing prebuilt modules
  Sources/swift-build-sdk-interfaces/main.swift
Labels: 🍒 release cherry pick

#1654 [6.0 🍒][Explicit Module Builds] Remove dead/incorrect code for handling header inputs of binary module dependencies
  Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
Labels: 🍒 release cherry pick, swift 6.0

#1578 Bump `swift-argument-parser` to 1.4.0
  Package.resolved
  Package.swift
Labels: dependencies
