Repository swiftlang/swift-driver, pull requests merged in 2025-03, with the labels that each got.

#1838 Added a getSingleFrontendInvocationFromDriverArgumentsV3 function whi…
  Sources/SwiftDriver/ToolingInterface/SimpleExecutor.swift
  Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
  Tests/SwiftDriverTests/SwiftDriverToolingInterfaceTests.swift
Labels: enhancement

#1840 NFC: Create `.editorconfig` to keep formatting consistent
  .editorconfig
Labels: NFC

#1841 Fix incorrect link job options for embedded WASI
  Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
  Tests/SwiftDriverTests/SwiftDriverTests.swift
Labels: embedded

#1852 Added a new `getSingleFrontendInvocationFromDriverArgumentsV4` function.
  Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
  Tests/SwiftDriverTests/SwiftDriverToolingInterfaceTests.swift
Labels: enhancement
